### ISSUE TITLE
Configure a branch other than master to use as base

### ISSUE THREAD

**Issue by timleslie** [atlassian/changesets#219] opened 2019-11-06 04:44 UTC
## Affected Packages

`@changesets/cli`

## Problem

When I run `yarn changeset` it tells me that *all* of my packages have changed and require a changeset. In reality, only some of them have changed. The root cause of this is that we use `dev` as our base branch name, rather than `master`. As such, when changesets calls `getMasterRef` it finds a ref from a very long time ago, which is where our `master` branch happens to be.

## Proposed solution

Allow the user to specify a `baseBranch` in `.changeset/config.json`, which defaults to `master`.

**Comment by mitchellhamilton** [comment] 2019-11-06 04:48
@Noviny If you have no problems with this, I'm happy to implement this because I've been wanting it recently

**Comment by mitchellhamilton** [comment] 2019-11-06 05:01
(My usecase is a pre-release branch being non-master)

**Comment by Noviny** [comment] 2019-11-06 10:51
This is a duplicate of #191 but yeah, happy for you to pick up this issue.

**Closed** 2019-11-07 23:19 UTC
Labels: enhancement, pkg:@changesets/cli
