### ISSUE TITLE
Add date to version changelog entry

### ISSUE THREAD

**Issue by JakeGinnivan** [atlassian/changesets#245] opened 2020-01-08 02:00 UTC
## Problem

I want to use changesets for a product rather than a library, in this case a date become as important (if not more) than the version number

## Proposed solution

Add `getVersionLine` hook into config to allow custom formatting of the version number to add additional context

**Comment by Noviny** [comment] 2020-01-21 05:53
Closed as a duplicate of #109

**Closed by Noviny** 2020-01-21 05:53 UTC
