### ISSUE TITLE
Unhandled error cause infinite loop in @changesets/git

### ISSUE THREAD

**Issue by leometzger** [atlassian/changesets#602] opened 2021-06-17 15:47 UTC
## Affected Packages

* @changesets/git

## Problem

In some git solutions like Bitbucket, `git fetch --deepen [Number]` does not work.

When the command `changeset version` is runned in a step from `bitbucket-pipeline`, that is using a shallow clone, the step locks.

This happens because the `changeset version` try to get more commits from history using the `git fetch --deepen` command

## Proposed solution

Throw an error if the returning code from `git fetch --deepen [Number]` is different from 0.

https://github.com/atlassian/changesets/blob/main/packages/git/src/index.ts#L165

**Comment by Andarist** [comment] 2021-06-18 21:19
duplicate of https://github.com/atlassian/changesets/issues/571

**Closed by Andarist** 2021-06-18 21:19 UTC
