### ISSUE TITLE
Getting "JavaScript heap out of memory" error on init

### ISSUE THREAD

**Issue by zkochan** [atlassian/changesets#302] opened 2020-03-26 14:21 UTC
## Problem

I wanted to try this project out on the [pnpm monorepo](https://github.com/pnpm/pnpm). In the root of the pnpm monorepo I installed the CLI through: `pnpm add -DW @changesets/cli`

Then I ran `pnpx changeset init`.

After a long wait, during which no output was printed to the terminal, the CLI failed with a `JavaScript heap out of memory` exception

**Comment by Andarist** [comment] 2020-03-26 16:58
Thank you for your report - gonna take a look.

**Comment by Andarist** [comment] 2020-03-26 22:37
This happens because some of your packages depend on themselves - which results in the directory tree of infinite depth (when we follow symlinks which reside in `node_modules`).

As to the init command - it doesn't require querying your packages at all, this line can just be moved a little bit further in the code and this would work but you would end up with the same problem rather quickly because changesets are querying for workspace packages basically when executing any command. 

I'm going to prepare a simple fix for this in a moment, **but** this still won't cover your setup entirely. The problem is that your globs are overly greedy anyway - and if it's possible I would advise changing them. If that's not possible then please let me know why it isn't so we can think of some solution for the problem. I'm talking about those globs listed [here](https://github.com/pnpm/pnpm/blob/c55f1bc8c1532ef0fec8f5e0e3e17674776dcbff/pnpm-workspace.yaml) - it would be much better if you could replace `/**` with `/*`.

If you do so the init command should stop blowing up but it will still fail for another reason - you have some nameless packages there - such as [`utils/updater`](https://github.com/pnpm/pnpm/blob/c55f1bc8c1532ef0fec8f5e0e3e17674776dcbff/utils/updater/package.json). There is currently a requirement for each package to have a name.

**Comment by zkochan** [comment] 2020-03-26 23:01
Thanks @Andarist 

After changing the globs and adding names to all the private packages in the monorepo, the `changeset init` command worked. So you may close this issue if you believe there's nothing to improve here.

I agree, that it is better to use the non-greedy pattern but I am surprised you have issues with them. pnpm works fine even with those greedy globs. We use [fast-glob](https://www.npmjs.com/package/fast-glob)

**Comment by mitchellhamilton** [comment] 2020-03-26 23:21
Yeah, we should definitely fix this.

@Andarist I think the fix should be to add `gitignore: true` to [these options](https://github.com/Thinkmill/manypkg/blob/3c0771d5889d187bf970cae5c5193547ceed06d7/packages/get-packages/src/index.ts#L201-L204)

**Comment by Andarist** [comment] 2020-03-27 08:15
@zkochan `fast-glob` is also used here, the difference is that you normalize patterns by appending `/package.json` (and co) to the input patterns. With those greedy patterns, this might also lead to broken results for packages containing multiple entries with additional package.json files. An example of that would be this: https://unpkg.com/@emotion/styled@11.0.0-next.12/base/package.json

> @Andarist I think the fix should be to add gitignore: true to these options

cool, was planning on ignoring `**/node_modules` but this is definitely a more neat solution

**Comment by Noviny** [comment] 2020-03-29 02:03
Closing as this is merged. Thanks a lot @Andarist

**Closed by Noviny** 2020-03-29 02:03 UTC

**Comment by LukasBombach** [comment] 2022-02-07 11:42
I am posting a reference to

https://github.com/gatsbyjs/gatsby/issues/22717#issuecomment-1031373588

here because I am getting heap out of memory crashes in a project that uses emotion and this seems to be a thing here and in that issue as well
