### ISSUE TITLE
`changeset version` replaces lower-bound with exact version

### ISSUE THREAD

**Issue by mxmul** [atlassian/changesets#230] opened 2019-12-17 19:44 UTC
## Affected Packages

@changesets/cli

## Problem

If I have two packages in a monorepo (`pkg-a` and `pkg-b`), and `pkg-b` depends on `pkg-a` with a lower-bounded version range, e.g:

```
$ cat packages/pkg-b/package.json
{
  "name": "pkg-b",
  "version": "1.0.0",
  "dependencies": {
      "pkg-a": ">=1.0.0"
  }
}
```

then applying a changeset that bumps both `pkg-a` and `pkg-b` results in the lower-bounded dependency being replaced with an exact version pin:

```
$ ./node_modules/.bin/changeset status
🦋  info Packages to be bumped at patch:
🦋  info
🦋  - pkg-a
🦋  - pkg-b
🦋  ---
🦋  info NO packages to be bumped at minor
🦋  ---
🦋  info NO packages to be bumped at major

$ ./node_modules/.bin/changeset version
🦋  All files have been updated. Review them and commit at your leisure

$ git diff
diff --git a/packages/pkg-a/package.json b/packages/pkg-a/package.json
index ee09b19..569f194 100644
--- a/packages/pkg-a/package.json
+++ b/packages/pkg-a/package.json
@@ -1,4 +1,4 @@
 {
   "name": "pkg-a",
-  "version": "1.0.0"
+  "version": "1.0.1"
 }
diff --git a/packages/pkg-b/package.json b/packages/pkg-b/package.json
index 23d79d5..06cd049 100644
--- a/packages/pkg-b/package.json
+++ b/packages/pkg-b/package.json
@@ -1,7 +1,7 @@
 {
   "name": "pkg-b",
-  "version": "1.0.0",
+  "version": "1.0.1",
   "dependencies": {
-      "pkg-a": ">=1.0.0"
+    "pkg-a": "1.0.1"
   }
 }
```
This is a problem, because it reduces the compatibility range of `pkg-b` on `pkg-a` and therefore increases the likelihood of dependency conflicts in external consumers of these packages. Practically, this means increased nesting in node_modules and potentially larger client-side JS builds.

## Proposed solution

`changeset version` should not touch the dependency ranges at all if the declared range is compatible with the new version in the monorepo.

**Comment by Noviny** [comment] 2019-12-19 00:12
Hi!

Thanks for bringing this up.

There's unfortunately an edge-casey thing that means several projects using changesets rely on the fact everything in a single release bumps dependencies on itself. We're unlikely to be able to shift that soonish. (The problem is captured in #117 )

What we should do though, is expand the version ranges we handle correctly. Currently we only handle absolute, tilde and caret dependencies, but issue #99 is to expand these out which would improve your use-case.

If you deliberately want to not update these packages, there's a way to modify the `releasePlan` before applying it, but it's quite custom right now and implementing it isn't well documented. Happy to guide you through doing that to solve for your case right now.

I'm going to close this issue, as I think the other two capture our likely direction around this better, but am happy to keep talking about it if this won't address your root problem, and reopen it if it looks like it won't be properly addressed by the above.

**Closed by Noviny** 2019-12-19 00:12 UTC
