### ISSUE TITLE
`changeset` process continues running when ended while waiting for external editor

### ISSUE THREAD

**Issue by with-heart** [atlassian/changesets#499] opened 2020-11-29 21:58 UTC
## Affected Packages

`@changesets/cli`

## Problem

Related to #498. The changeset cli fails to run my external editor and simply hangs. Escaping the process using `^C` does not end the process and it continues consuming a decent amount of CPU in the background.

![image](https://user-images.githubusercontent.com/1954752/100554646-fd6f1a00-3263-11eb-8ebb-31b9c60c22e7.png)

Sometimes the process is listed as `changeset` and other times it's listed as `node`. Not entirely sure what causes the difference.

**Comment by Andarist** [comment] 2020-11-29 23:01
Could you list the exact required steps to reproduce the problem? It would make it easier for me to try debugging this.

**Comment by with-heart** [comment] 2020-11-29 23:31
> Could you list the exact required steps to reproduce the problem? It would make it easier for me to try debugging this.

Absolutely!

1. `export EDITOR=vim` to set editor to terminal-based process
2. Run `changeset` cli
3. Select a package and a version to bump
4. At "Summary" line, press enter to open external editor
5. Nothing happens, so <kbd>Ctrl</kbd><kbd>C</kbd> to escape
6. Find process still running in the background (was able to find it locally with `ps aux | grep changeset`)

Repeat 2-5 a few times and you should find a running process for each.

**Comment by pkieltyka** [comment] 2021-01-20 13:59
same issue over here

**Comment by Andarist** [comment] 2021-01-20 23:09
I've just tried this using the provided repro steps and I wasn't able to repro this - would any of you be willing to setup a call with me to hunt this down?

**Comment by with-heart** [comment] 2021-01-20 23:12
@Andarist Absolutely!

**Comment by Andarist** [comment] 2021-01-23 10:14
It seems that the root cause is the same as https://github.com/atlassian/changesets/issues/498 so let's keep that other issue open and close this one for now. I've reported the issue to the package we are using here: https://github.com/mrkmg/node-external-editor/issues/24

**Closed by Andarist** 2021-01-23 10:14 UTC
