### ISSUE TITLE
Pre mode version incorrect

### ISSUE THREAD

**Issue by JakeGinnivan** [atlassian/changesets#244] opened 2020-01-06 12:36 UTC
## Affected Packages

https://github.com/sevenwestmedia/project-watchtower

There is only a single package currently.

## Problem

I committed pre.json onto master

pre.json
```
{
  "mode": "pre",
  "tag": "beta",
  "initialVersions": {
    "project-watchtower": "1.6.0"
  },
  "changesets": [
    "beige-islands-fry",
    "poor-dragons-act",
    "twelve-olives-burn",
    "unlucky-flowers-wave",
    "young-jokes-wink"
  ]
}
```

package.json

```
{
    "name": "project-watchtower",
    "version": "2.0.0-beta.0",
```

With the above, the changelog for the version command generated 1.6.1-beta.1, I was expecting 2.0.0-beta.1

## Proposed solution

I haven't looked too much into this project yet, have some other focuses atm, but thought I'd report the issue for now.

**Comment by Andarist** [comment] 2020-01-23 06:40
I dont think pre mode should be tied to making new majors only. There are valid reasons to publish prereleases of even patch versions. I believe this is computed based on  your changesets so if you add a changeset with major type then you whould get your expected result.

**Comment by Noviny** [comment] 2020-01-24 02:39
Hi! I just did some experimenting in your project - quick question, how did you get your `pre.json`

I deleted the `pre.json` and set the version back to `1.6.0` and then ran

```
yarn changeset pre enter beta   
```

which gave me

```
{
  "mode": "pre",
  "tag": "beta",
  "initialVersions": {
    "project-watchtower": "1.6.0"
  },
  "changesets": []
}
```

Running `yarn changeset version` here worked as intended, updating the version to `2.0.0-beta.0` and the `pre.json` to

```
{
  "mode": "pre",
  "tag": "beta",
  "initialVersions": {
    "project-watchtower": "1.6.0"
  },
  "changesets": [
    "beige-islands-fry",
    "fair-bats-destroy",
    "loud-monkeys-think",
    "poor-actors-rule",
    "poor-dragons-act",
    "twelve-olives-burn",
    "unlucky-flowers-wave",
    "weak-pandas-draw",
    "young-jokes-wink"
  ]
}
```

---

Tried a couple of different things and couldn't reproduce your case - do you have a particular commit this errored on?

Closing for now as couldn't reproduce.

**Comment by JakeGinnivan** [comment] 2020-01-26 01:24
Hey, sorry for being quiet on this one.

The initial version worked great, it was when trying to produce beta.1.

Steps to reproduce:

1) Enter pre beta with a major changeset
2) Release
3) Add another changeset, it should be a minor change
4) Release version will be 1.6.0-beta.1, expected 2.0.0-beta.1

The pre-release bumps as expected, but the version calculation didn't seem to take into account that that beta had already released major versions, and instead did a minor bump against the initial version?

**Comment by JakeGinnivan** [comment] 2020-01-26 01:30
I think the root cause would be that the `yarn changeset version` needs to take the package.json version, not just pre-release number, into account when calculating the version number?

@Andarist hope this clarifies, it's not that I want it to always be a major, it's just if I start releasing a major I have to make all changesets major, otherwise it drops the version back to the initial

**Comment by mitchellhamilton** [comment] 2020-01-26 04:33
I just tried to reproduce it and was able to, I'll have a look

**Closed** 2020-01-31 05:00 UTC

**Comment by JakeGinnivan** [comment] 2020-02-03 02:48
Thanks for this!
